# Generated by Django 4.2.27 on 2026-01-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='post',
            name='workout',
            field=models.CharField(blank=True, choices=[('run', 'RUN'), ('cycle', 'CYCLE'), ('row', 'ROW'), ('swim', 'SWIM'), ('yoga', 'YOGA'), ('pilates', 'PILATES'), ('functional strength', 'FUNCTIONAL STRENGTH'), ('other', 'OTHER')], max_length=20),
        ),
    ]
